### ISSUE TITLE
Feature request: Hide held packages when running `sfsu status` with an argument (e.g. -h)

### ISSUE THREAD

**Issue by mizzuri** [winpax/sfsu#700]
## Is your feature request related to a problem? Please describe

Not a problem.

## Describe the solution you'd like

When the `sfsu status` command is invoked, it displays the statuses of all packages, including those that are on hold. While this behavior is intentional, I would like to hide the packages that are on hold for the sake of clarity.
And of course, when it is run with an additional argument, e.g. `-h`.

## Describe alternatives you've considered
I've tried the following, but it doesn't work:
```
sfsu status | Where-Object { $_.Name -notlike '*Held package*' }
```
## Additional context

I have several packages on hold, and it'd be nice just to see the ones that matter. 
`Thank you!`

**Comment by jewlexx** [comment]
Sounds good.

> sfsu status | Where-Object { $_.Name -notlike '*Held package*' }

Just a note on this, passing sfsu output to PowerShell as an object won't work because of how PowerShell handles outputs. Scoop by default displays most results as PowerShell objects, which is where the pretty output comes from, but sfsu has custom tables and what not for this kind of stuff. I've tried mimicking PowerShell output to see if it can interpret it as an object but as far as I can tell PowerShell holds some metadata about command outputs, rather than just parsing a string.

What you can do is convert the json output from sfsu into a PowerShell object:
`sfsu status --json | ConvertFrom-Json`
