### ISSUE TITLE
Different result with search command

### ISSUE THREAD

**Issue by max7pro** [winpax/sfsu#772]
Please help to understand what difference in search method between "sfsu search" and "scoop search". Bunch of scoop + sfsu is my main tool for package managing, I like it, so it will be good idea to understand what I can skip during search 
On screenshot I attached you can see example. "Invoke-Expression (&sfsu hook)" line is not added to PS profile file, so scoop uses its own search command, which is different from "sfsu search" in current case.

![image](https://github.com/winpax/sfsu/assets/145686781/8b7e346a-b31f-49bd-91a2-71446af76c40)

Thank you in advance for your help and for cool sfsu tool.

**Comment by jewlexx** [comment]
Scoop by default searches both binaries and package names, so in the example above, `htc` matches `htcacheclean.exe` but not `apache`.

sfsu defaults to just matching names because matching binaries or both is rather slow, but to get this behavior you can add `-m binaries` or `-m both` to match just binaries, or both names and binaries respectively.
